name: tech_salaries_cpu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - matplotlib
  - pip
  - pip:
      - polars
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch
      - torchvision
      - torchaudio