name: tech_salaries_gpu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - matplotlib
  - pip
  - pip:
      - polars
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch
      - torchvision
      - torchaudio